CREATE TABLE
    FordMunstangs (
        Id INTEGER NOT NULL PRIMARY KEY,
        name VARCHAR(42) NOT NULL,
        PowerSteering VARCHAR(46) NOT NULL,
        FrontBrakes VARCHAR(27) NOT NULL,
        RearBrakes VARCHAR(27) NOT NULL,
        SpecialPackage VARCHAR(465) NOT NULL,
        MainImgUrl VARCHAR(274) NOT NULL,
        ImageUrls0 VARCHAR(271) NOT NULL,
        ImageUrls1 VARCHAR(259) NOT NULL,
        ImageUrls2 VARCHAR(242) NOT NULL,
        ImageUrls3 VARCHAR(280) NOT NULL,
        ImageUrls4 VARCHAR(242) NOT NULL,
        Generation VARCHAR(32) NOT NULL,
        Engine VARCHAR(47) NOT NULL,
        ProductionYear INTEGER NOT NULL,
        EndYear INTEGER NOT NULL,
        BodyType VARCHAR(20) NOT NULL,
        EngineArchitecture VARCHAR(179) NOT NULL,
        NumberSeats INTEGER NOT NULL,
        NumberDoors INTEGER NOT NULL,
        FuelType VARCHAR(8) NOT NULL,
        Power VARCHAR(17) NOT NULL,
        Displacement VARCHAR(14) NOT NULL,
        NumberCylinders INTEGER NOT NULL,
        EngineConfiguration VARCHAR(93) NOT NULL,
        FuelInjectionSystem VARCHAR(31) NOT NULL,
        Distributor VARCHAR(24) NOT NULL,
        EngineOilCapacity VARCHAR(13) NOT NULL,
        Length VARCHAR(7) NOT NULL,
        Width VARCHAR(7) NOT NULL,
        Height VARCHAR(7) NOT NULL,
        Wheelbase VARCHAR(7) NOT NULL,
        TurningDiameter VARCHAR(13) NOT NULL,
        PropulsionArchitecture VARCHAR(69) NOT NULL,
        Drivetrain VARCHAR(17) NOT NULL,
        FrontSuspension VARCHAR(74) NOT NULL,
        RearSuspension VARCHAR(46) NOT NULL,
        SteeringType VARCHAR(44) NOT NULL,
        TiresAndRimSizeSize VARCHAR(67) NOT NULL,
        Trim VARCHAR(36) NOT NULL,
        price INTEGER NOT NULL
    );